<a href="https://colab.research.google.com/github/Smrt44/python/blob/main/4_loc_iloc_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pandas: `loc` and `iloc`

Learn how to select rows and columns, run simple examples, and then solve the practice questions in the empty code cells.

In [ ]:
import pandas as pd

#### 1. Create a Sample DataFrame

In [ ]:
data = {
    "ID": [101, 102, 103, 104],
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)
df

    ID  Name  Marks
0  101   Ram     85
1  102  Sita     90
2  103  Hari     78
3  104  Gita     92

**Set `ID` as the index**

This makes the row labels `101`, `102`, `103`, and `104` instead of the default `0`, `1`, `2`, and `3`.

In [ ]:
df = df.set_index("ID")
df

#### 2. `loc` — Label-Based Selection

`loc` selects data using **row labels** and **column names**, not row positions.

- A row can be selected using its ID label, such as `101`.
- A column can be selected by its name, such as `"Name"`.
- For label slices such as `101:103`, **both endpoints are included** in this example.

**Select one row by label**

In [ ]:
# Row whose index label is 101
df.loc[101]

**Select one value by row and column labels**

In [ ]:
# Name of the student with ID 101
df.loc[101, "Name"]

**Select multiple rows by labels**

In [ ]:
# Rows with ID 101 and 103
df.loc[[101, 103]]

**Select a range of rows and specific columns**

In [ ]:
# Includes IDs 101, 102, and 103
df.loc[101:103, ["Name", "Marks"]]

**Select the same column for all rows**

In [ ]:
# Select the Marks column using its label
df.loc[:, "Marks"]

#### `loc` Practice

Use the DataFrame named `df`. Write the solution below each question.

In [ ]:
# Q1. Display the row of the student whose ID is 102 using loc.
# Write your code below:

In [ ]:
# Q2. Display only the Marks of the student whose ID is 104 using loc.
# Write your code below:

In [ ]:
df

    ID  Name  Marks
0  101   Ram     85
1  102  Sita     90
2  103  Hari     78
3  104  Gita     92

In [ ]:
# Q3. Display the rows for IDs 102 and 104 using loc.
# Write your code below:
df.loc[[102, 104]]

KeyError: "None of [Index([102, 104], dtype='int64')] are in the [index]"

In [ ]:
# Q4. Display Name and Marks for all students from ID 102 to 104 using loc.
# Write your code below:

#### 3. `iloc` — Integer Position-Based Selection

`iloc` selects data using **integer positions** rather than index labels.

- Row positions start at `0`.
- Column positions also start at `0`.
- In a slice such as `0:3`, the final position (`3`) is **excluded**.

Our DataFrame still has row labels `101`–`104`, but its positions are `0`–`3`.

**Display the DataFrame before using `iloc`**

In [ ]:
df

**Select one row by position**

In [ ]:
# First row (ID 101)
df.iloc[0]

**Select multiple rows by positions**

In [ ]:
# First and third rows (positions 0 and 2)
df.iloc[[0, 2]]

**Select one value by row and column positions**

In [ ]:
# Second row, first column: Sita
df.iloc[1, 0]

**Select a range of rows and columns**

In [ ]:
# Rows at positions 0, 1, 2 and columns at positions 0, 1
df.iloc[0:3, 0:2]

**Select one column by position**

In [ ]:
# Second column (Marks) for all rows
df.iloc[:, 1]

#### `iloc` Practice

Use integer positions only. Write your answers in the blank cells.

In [ ]:
# Q1. Display the fourth row using iloc.
# Write your code below:

In [ ]:
# Q2. Display the first and third rows using iloc.
# Write your code below:

In [ ]:
# Q3. Display the Marks of the second student using iloc.
# Write your code below:

In [ ]:
# Q4. Display the first two rows with both columns using iloc.
# Write your code below:

#### 4. `loc` vs. `iloc` — Quick Comparison

| Feature | `loc` | `iloc` |
| --- | --- | --- |
| Selects by | Row and column **labels** | Row and column **positions** |
| Row example | `df.loc[101]` | `df.iloc[0]` |
| Single value | `df.loc[101, "Name"]` | `df.iloc[0, 0]` |
| Slice endpoint | Included (for this index) | Excluded |
| Useful when | You know IDs or column names | You know row/column positions |

#### 5. Common Mistakes

**Mistake 1:** Using an ID label like `101` as a position:

```python
df.iloc[101]  # IndexError: only 4 rows (positions 0–3)
```

**Mistake 2:** Using position `0` as a label after setting `ID` as the index:

```python
df.loc[0]  # KeyError: 0 is not a row label
```

**Remember:** For this DataFrame, `df.loc[101]` and `df.iloc[0]` select the same first row in different ways.

#### 6. Final Practice

Choose either `loc` or `iloc` for each task and write the code in the space provided.

In [ ]:
# Q1. Display the Name of the student whose ID is 103.
# Write your code below:

In [ ]:
# Q2. Display the last two rows using their positions.
# Write your code below:

In [ ]:
# Q3. Display all students' Name and Marks columns using labels.
# Write your code below:

**Key takeaway:** `loc` = **labels**; `iloc` = **integer positions**.